### ISSUE TITLE
Object of type 'datetime' is not JSON serializable

### ISSUE THREAD

**Issue by gekart** [giantswarm/yaml-jq#1]
The file below will throw an exception (since YAML is a superset of JSON):

```
cat test.yaml | docker run -i giantswarm/yaml-jq:0.1.0 '.spec.api.loadBalancer.type'
TypeError: Object of type 'datetime' is not JSON serializable
```

```
test.yaml:
metadata:
  creationTimestamp: 2017-10-11T09:55:41Z
  name: xyz
spec:
  api:
    loadBalancer:
      type: Public
```
